# ALGORİTMA ÖRNEKLERİ
Kodlab yayinlarinin algoritma ve programlama mantıgı isimli kitabindaki algoritma ornkeklerinin python dilinde yazilmiş halleri.

## DİZİ (LİSTE) UYGULAMALARI

### KLAVYEDEN ALINAN SAYILARI BİR DİZİYE AKTARMA
Problem açıklaması: Klavyeden alınacak 10 adet sayıyı, daha önce tanımlanmış olan bir diziye/listeye aktaran programı yazınız.

In [21]:
liste = []
sayac = 0
while (sayac < 10):
    sayi = int(input("Listeye aktarilacak sayi giriniz: "))
    liste.append(sayi)
    sayac = sayac + 1
    
print("Liste = ", liste)

Listeye aktarilacak sayi giriniz:  127
Listeye aktarilacak sayi giriniz:  378
Listeye aktarilacak sayi giriniz:  457
Listeye aktarilacak sayi giriniz:  0
Listeye aktarilacak sayi giriniz:  675
Listeye aktarilacak sayi giriniz:  363546634
Listeye aktarilacak sayi giriniz:  3
Listeye aktarilacak sayi giriniz:  888
Listeye aktarilacak sayi giriniz:  768
Listeye aktarilacak sayi giriniz:  45794


Liste =  [127, 378, 457, 0, 675, 363546634, 3, 888, 768, 45794]


### BİR DİZİNİN TÜM ELEMANLARINI EKRANA YAZDIRMA
Problem açıklaması: Tanımlanmış ve içi dolu alarak varsayılan bir dizinin/listenin tüm elemanlarına ulaşan ve ekrana yazdıran programı yazınız.

In [43]:
liste = [8,10,56,12,3,5,8,1,74,6,11,89]
sayac = 0
for eleman in liste:
    sayac = sayac + 1
    print("{}. elamanin degeri: ".format(sayac),eleman)


1. elamanin degeri:  8
2. elamanin degeri:  10
3. elamanin degeri:  56
4. elamanin degeri:  12
5. elamanin degeri:  3
6. elamanin degeri:  5
7. elamanin degeri:  8
8. elamanin degeri:  1
9. elamanin degeri:  74
10. elamanin degeri:  6
11. elamanin degeri:  11
12. elamanin degeri:  89


### BİR DİZİNİN TÜM ELEMANLARI TOPLAMINI HESAPLAMA
Problem açıklaması: Tam sayıları baarındıran bir dizinin/listenin içerisindeki tüm sayıları toplayan ve ekrana yazdıran programı yazınız.

In [67]:
liste = [2,5,12,17,8,9,1,33]
toplam = sum(liste)
for eleman in liste:
    print("{}".format(eleman), end = "+")
print(" =", toplam)    

2+5+12+17+8+9+1+33+ = 87


### BİR DİZİNİN TÜM ELEMANLARINI BİR KATSAYI İLE ÇARPMA
Problem açıklaması: Bir dizinin/listenin tüm elemanlarını, klavyeden girilecek bi k katsayısı ile çarpan ve dizinin eski haliyle yeni halini ekrana yazdıran program.

In [40]:
A = [1900,2200,2360,2400,3600,3950,4450,4750,4900,6000]
B = [len(A)]
k = float(input("Maas zammi icin bir katsayi (k) giriniz: "))

B = [A[i]*k for i in range(len(A))]
    
print("\tESKİ\tYeni\tZam\n\n")

for i in range(0, len(A)):
    print("\t", A[i], "TL\t", B[i], "TL\t", (B[i] - A[i]), "TL")

Maas zammi icin bir katsayi (k) giriniz:  1.3


	ESKİ	Yeni	Zam


	 1900 TL	 2470.0 TL	 570.0 TL
	 2200 TL	 2860.0 TL	 660.0 TL
	 2360 TL	 3068.0 TL	 708.0 TL
	 2400 TL	 3120.0 TL	 720.0 TL
	 3600 TL	 4680.0 TL	 1080.0 TL
	 3950 TL	 5135.0 TL	 1185.0 TL
	 4450 TL	 5785.0 TL	 1335.0 TL
	 4750 TL	 6175.0 TL	 1425.0 TL
	 4900 TL	 6370.0 TL	 1470.0 TL
	 6000 TL	 7800.0 TL	 1800.0 TL


### İKİ DİZİNİN TÜM ELEMANLARINI KARŞILIKLI OLARAK TOPLAMA
Problem açıklaması: İçleri dolu iki ayrı dizinin/listenin tüm elemanlarının karşılıklı olarak toplayan ve ekrana yazdıran programı yazınız.

In [100]:
A = [12,18,22,10,88,25]
B = [38,11,14,5,20,13]
C = []
C = [sum(i) for i in zip(A,B)]

print("\t A + B = C \n")

for i in range(0, len(A)):
    print("\t", A[i], " + ", B[i], " = ", C[i])

	 A + B = C 

	 12  +  38  =  50
	 18  +  11  =  29
	 22  +  14  =  36
	 10  +  5  =  15
	 88  +  20  =  108
	 25  +  13  =  38


### BİR DİZİDEKİ İKİ ELEMANIN YERİNİ DEĞİŞTİRME
Problem açıklaması: Bir dizide, klavyeden alınan indis numaralarına karşlık gelen sayıların yerlerini değiştiren ve dizinin son halini ekrena yazdıran programı yazınız.

In [109]:
liste = [1,2,3,4,5,6,7,8,9]
a = int(input("Birinci index (a) giriniz: "))
b = int(input("Ikinci index (b) giriniz: "))

temp = liste[a]
liste[a] = liste[b]
liste[b] = temp

for i in range(0, len(liste)):
    print(liste[i], end = " ")

Birinci index (a) giriniz:  0
Ikinci index (b) giriniz:  8


9 2 3 4 5 6 7 8 1 

### BİR DİZİYİ TESRİNE ÇEVİRME
Problem açıklaması: Bir diziyi/listeyi tersine çeviren ve dizinin/listenin tam halini ekrana yazdıran programı yazınız.

In [10]:
liste = [1,2,3,4,5,6,7,8,9,10]
boyut = len(liste)

for i in range(0, int(boyut/2)):
    temp = liste[i]
    liste[i] = liste[boyut-i-1]
    liste[boyut-i-1] = temp
    
for i in range(0, boyut):
    print(liste[i], end = " ")

10 9 8 7 6 5 4 3 2 1 

### BİR DİZİ İÇERİSİNDE ARAMA YAPMA
Problem açıklaması: Klavyeden alınan sayının, dizide/listede var olup olmadığını kontrol eden ve bu durumu ekrana yazdıran programı yazınız.

In [11]:
liste = [1,2,3,4,5,6,7,8,9,10]
ara, yer = -1, -1
ara = int(input("Aramak istediginiz sayiyi giriniz: "))
for i in range(0, len(liste)):
    if (liste[i] == ara):
        yer = i
        break
        
if (yer != -1):
    print("Aranilan eleman bulundu index numarası: ", yer)
else:
    print("Aranilan eleman bulunamadi.")

Aramak istediginiz sayiyi giriniz:  5


Aranilan eleman bulundu index numarası:  4


### BİR DİZİNİN EN BUYUK VE EN KUCUK ELEMANLARINI BULMA
Problem açıklaması: İçerisinde tam sayılar olan bir dizinin/listenin en büyük ve en küçük elemanını bulan ve ekrena  yazdıran programı yazınız.

In [12]:
liste = [1,2,3,4,5,6,7,8,9,10]
kucuk = liste[0]
buyuk = liste[0]
for i in range(0, len(liste)):
    if (liste[i] < kucuk):
        kucuk = liste[i]
    if (liste[i] > buyuk):
        buyuk = liste[i]
        
print("En kucuk deger: ", kucuk)
print("En buyuk deger: ", buyuk)

En kucuk deger:  1
En buyuk deger:  10


### BİR KELİMEYİ ASCII TABLOSUNA GÖRE ŞİFRELEME
Problem açıklaması: Büyük harfler ile yazılmış bir kelimeyi ASCII tablosuna göre şifreleyen ve şifrelenmiş halini ekrana yazdıran programı yazınız.

In [49]:
kelime = input("Bir kelime giriniz: ").upper()
yeni = ""

for harf in kelime:
    if (harf == " "):
        yeni += " "
    elif (ord(harf) + 5 > ord("Z")):
        yeni += chr(ord(harf) + 5 - 26)
    else:
        yeni += chr(ord(harf) + 5)
        
print(yeni)

Bir kelime giriniz:  Python


UDYMTS


### BİR DİZİYİ RASTGELE SAYILARLA DOLDURMA
Problem açıklaması: Klavyeden girilen eleman sayısına göre bir dizi/liste oluşturan ve bu dizinin/listenin tüm elemanlarını rastgele sayılarla dolduran programı yazınız.

In [27]:
import random
n = int(input("Eleman sayisi (n) giriniz: "))

sayilar = []

for i in range(n):
    sayilar.append(random.randint(0,100))
    
for i in range(0, n):
    print(sayilar[i], end = " ")

Eleman sayisi (n) giriniz:  10


77 76 55 59 14 31 28 97 63 91 

### BİR DİZİDE KAÇ ADET TEK, ÇİFT VE ASAL SAYI OLDUĞUNU BULMA
Problem açıklaması: Bir dizi/liste içerisindeki sayılardan kaç tanesinin tek, çift ve asal sayı olduğunu bulan ve ekrana yazandıran programı yazınız.

In [16]:
s = [22,36,12,44,56,96,34,23,47,85,76,13,19,45,48,53,7]
tek, cift, asal = 0, 0, 0

for i in range(0, len(s)):
    sayi = s[i]
    if (sayi %2 == 0):
        cift = cift + 1
    bolen = 0
    
    for j in range(1, sayi):
        if (sayi %j == 0):
            bolen = bolen + 1
    if (bolen == 1):
        asal = asal + 1
        
tek = len(s) - cift

print("Toplam cift sayi: ", cift)
print("Toplam tek sayi: ", tek)
print("Toplam asal sayi: ", asal)

Toplam cift sayi:  9
Toplam tek sayi:  8
Toplam asal sayi:  6


### BİR KELİMDE HANGİ HARFTEN KAÇ ADET GEÇTİĞİNİ BULMA
Problem açıklaması: Klavyeden küçük harfle ile girilecek bir kelimenin içerisinde hangi harften kaç tane geçtiğini tespit eden ve ekrana bastıran programı yazınız.

In [75]:
from collections import Counter

kelime = str(input("Bir kelime giriniz: "))

print(collections.Counter(kelime))

Bir kelime giriniz:  algoritma


Counter({'a': 2, 'l': 1, 'g': 1, 'o': 1, 'r': 1, 'i': 1, 't': 1, 'm': 1})


### BİR DİZİDEKİ SAYILARI KÜÇÜKTEN BÜYÜĞE SIRALAMA
Problem açıklaması: Klavyeden girilen sayılar ile bir dizi/liste oluşturup, bu diziyi küçükten büyüğe sıralayan ve yeni halini ekrana bastıran programı yazınız.

In [ ]:
liste = []
N = int(input("Eleman sayisi giriniz: "))
for i in range(N):
    sayi = int(input("Listeye aktarilacak sayi giriniz: "))
    liste.append(sayi)
    
liste.sort()
print("------ Siralanmis Liste ------")
print("Liste = ", liste)

Eleman sayisi giriniz:  7
Listeye aktarilacak sayi giriniz:  0
Listeye aktarilacak sayi giriniz:  124
Listeye aktarilacak sayi giriniz:  457568657
Listeye aktarilacak sayi giriniz:  234
Listeye aktarilacak sayi giriniz:  123
Listeye aktarilacak sayi giriniz:  465805
Listeye aktarilacak sayi giriniz:  2


------ Siralanmis Liste ------
Liste =  [0, 2, 123, 124, 234, 465805, 457568657]


### BİR MATRİS OLUŞTURMA VE DEĞERLERİNİ KLAVYEDEN OKUMA
Problem açıklaması: Klavyeden girilen N değerine göre $NxN$ boyutunda bir kare matris oluşturuan ve klavyeden tüm değerleri okuyan programı yazınız.

In [1]:
sutun = int(input("Sutun giriniz: "))
satır = int(input("Satir giriniz: "))

matrix = []
print("Sira ile giris yapiniz:")

for i in range(sutun):          
    a =[]
    for j in range(satır):     
         a.append(int(input()))
    matrix.append(a)

for i in range(sutun):
    for j in range(satır):
        print(matrix[i][j], end = " ")
    print()

Sutun giriniz:  3
Satir giriniz:  3


Sira ile giris yapiniz:


 5
 4
 3
 3
 2
 7
 5
 4
 5


5 4 3 
3 2 7 
5 4 5 


### BİR MATRİSİN TÜM ELEMANLARI TOPLAMINI HESAPLAMA
Problem açıklaması: Değerleri klavyeden girilen bir matrisin tüm elamanları toplamını hesaplayan ve ekrana yazdıran programı yazınız.

In [15]:
import numpy as np
sutun = int(input("Sutun giriniz: "))
satır = int(input("Satir giriniz: "))

matrix = []
print("Sira ile giris yapiniz:")

for i in range(sutun):          
    a =[]
    for j in range(satır):     
         a.append(int(input()))
    matrix.append(a)

for i in range(sutun):
    for j in range(satır):
        print(matrix[i][j], end = " ")
    print()
print("Matrix: \n", matrix)
print("\nThe sum of the matrix is: ", np.sum(matrix))   

Sutun giriniz:  2
Satir giriniz:  2


Sira ile giris yapiniz:


 1
 2
 3
 4


1 2 
3 4 
Matrix: 
 [[1, 2], [3, 4]]

The sum of the matrix is:  10


### BİR MATRİSİN TRANSPOZUNU BULMA
Açıklama: Bir matrisin transpozunu elde etmek için, söz konusu matrisin satır ve sütunlarının yer değiştirilmesi gerekir.

In [21]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Orjinal hali: \n{matrix}') #f-string yapisinıi kullandik. .format yapisinin daha duzenli hali denebilir.

T = arr1.transpose()

print(f'Transpozu alimis matrix: \n{T}')

Orjinal hali: 
[[1 2 3]
 [4 5 6]]
Transpozu alimis matrix: 
[[1 4]
 [2 5]
 [3 6]]


### BİRİM MATRİS OLUŞTURMA
Problem açıklması: Klavyeden girilen satır ve sütun sayısına (N) göre matris oluşturan ve bu matrisi ekrana yazdıran programı yazınız.

In [40]:
boyut = int(input("Boyut bilgisi giriniz: ")) 

for satir in range(0, boyut):
    for sutun in range(0, boyut):
        if (satir == sutun):
            print("1 ", end=" ")
        else:
            print("0 ", end=" ")
    print()      

Boyut bilgisi giriniz:  5


1  0  0  0  0  
0  1  0  0  0  
0  0  1  0  0  
0  0  0  1  0  
0  0  0  0  1  


### INSERTION SORT İLE DİZİDEKİ SAYILARI SIRALAMA
Insertion sort hakkında bilgi edinmek için [buraya](https://en.wikipedia.org/wiki/Insertion_sort) bakabilirsin.

Insertion sort akış diyagramı için ise [buraya](https://www.softwareideas.net/a/1604/insertion-sort-flowchart-) bakabilirsin.

In [8]:
liste = [8, 11, 64, 99, 0, 13]
 
for i in range(1, len(liste)):
    anahtar = liste[i]
    j = i-1
    while j >=0 and anahtar < liste[j] :
            liste[j+1] = liste[j]
            j -= 1
    liste[j+1] = anahtar
    
bos_liste = [] 
print("Siralanmis liste: ")
for i in range(len(liste)):
    bos_liste.append(liste[i])     
print(bos_liste)

Siralanmis liste: 
[0, 8, 11, 13, 64, 99]


### BUBBLE SORT İLE DİZİDEKİ SAYILARI SIRALAMA
Bubble sort hakkında bilgi edinmek için [buraya](https://en.wikipedia.org/wiki/Bubble_sort) bakabilirsin.

Bubble sort akış diyagramı için ise [buraya](https://www.softwareideas.net/a/1598/bubble-sort-flowchart-) bakabilirsin.

In [17]:
liste = [7,8,5,2,4,6,3]

for i in range(0, len(liste)-1):
    for j in range(0,len(liste)-1-i):
        if (liste[j+1] < liste[j]):
            temp = liste[j+1]
            liste[j+1] = liste[j]
            liste[j] = temp
            
print("Siralanmis liste: ")
for i in range(0,len(liste)):
    print(liste[i], end = " ")

Siralanmis liste: 
2 3 4 5 6 7 8 

### QUİCK SORT İLE DİZİDEKİ SAYILARI SIRALAMA
Quick sort hakkında bilgi edinmek için [buraya](https://en.wikipedia.org/wiki/Quick_sort) bakabilirsin.

Quick sort akış diyagramı için ise [buraya](https://atechdaily.com/posts/Quick-Sort-Algorithm-and-Flowchart-with-implementation-in-Java) bakabilirsin.

In [13]:
def quicksort(liste):
    if len(liste) < 2:
        return liste

    anahtar = liste[0]
    sol = list(filter(lambda x: x <= anahtar, liste[1:]))
    sag = list(filter(lambda x: x > anahtar, liste[1:]))
    
    return quicksort(sol) + [anahtar] + quicksort(sag)

liste = [7,8,5,2,4,6,3,111]
quicksort(liste)

[2, 3, 4, 5, 6, 7, 8, 111]